# permissions for end users to edit podpresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podpreset-editor-role
rules:
  - apiGroups:
      - wzrdtalesscp.wzrdtales.com
    resources:
      - podpresets
      - clusterpodpresets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - wzrdtalesscp.wzrdtales.com
    resources:
      - podpresets/status
      - clusterpodpresets/status
    verbs:
      - get
