# permissions for end users to view podpresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podpreset-viewer-role
rules:
  - apiGroups:
      - wzrdtalesscp.wzrdtales.com
    resources:
      - podpresets
      - clusterpodpresets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - wzrdtalesscp.wzrdtales.com
    resources:
      - podpresets/status
      - clusterpodpresets/status
    verbs:
      - get
